version: "3.9"

services:
  nginx_cert:
    container_name: nginx_cert
    image: nginx:1.27.1-alpine3.20-slim
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
    ports:
      - 80:80
    volumes:
      - ./volume/nginx_fallback:/etc/nginx
      - /var/log/nginx_fallback:/var/log/nginx
    command: ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx_cert.conf"]

  nginx_fallback:
    container_name: nginx_fallback
    image: nginx:1.27.1-alpine3.20-slim
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
    ports:
      - 80:80
    expose:
      - 8080
    volumes:
      - ./volume/nginx_fallback:/etc/nginx
      - /var/log/nginx_fallback:/var/log/nginx
    command: ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx_fallback.conf"]

  xray:
    container_name: xray
    image: ghcr.io/xtls/xray-core:24.10.31
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
    ports:
      - 443:443
    volumes:
      - ./volume/xray:/etc/xray
      - /var/log/xray:/var/log/xray